// <auto-generated />
using System;
using BookMyEvent.Services.Discount.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookMyEvent.Services.Discount.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20201230124606_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookMyEvent.Services.Discount.Entities.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlreadyUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = new Guid("64709060-67ae-4541-89ec-625c72fe743d"),
                            AlreadyUsed = false,
                            Amount = 10,
                            Code = "BeNice"
                        },
                        new
                        {
                            CouponId = new Guid("505421e6-dae5-47cf-88f6-6f84c5d32601"),
                            AlreadyUsed = false,
                            Amount = 20,
                            Code = "Awesome"
                        },
                        new
                        {
                            CouponId = new Guid("fb2d6cdb-8a10-4412-b649-c0441db4c47f"),
                            AlreadyUsed = false,
                            Amount = 100,
                            Code = "AlmostFree"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
