// <auto-generated />
using System;
using BookMyEvent.Services.Discount.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookMyEvent.Services.Discount.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20210106131045_UpdatedDiscountDb")]
    partial class UpdatedDiscountDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookMyEvent.Services.Discount.Entities.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = new Guid("3f7dbbba-aecc-4f39-9a86-0a3f8a73396d"),
                            Amount = 10,
                            UserId = new Guid("e455a3df-7fa5-47e0-8435-179b300d531f")
                        },
                        new
                        {
                            CouponId = new Guid("66e52ca9-6ab5-49a2-bed0-55eefabb73a9"),
                            Amount = 20,
                            UserId = new Guid("bbf594b0-3761-4a65-b04c-eec4836d9070")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
