// <auto-generated />
using System;
using BookMyEvent.Services.Discount.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookMyEvent.Services.Discount.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20210102185525_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookMyEvent.Services.Discount.Entities.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlreadyUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = new Guid("38086843-ada1-4f91-9fb4-79412cb57066"),
                            AlreadyUsed = false,
                            Amount = 10,
                            Code = "BeNice"
                        },
                        new
                        {
                            CouponId = new Guid("e493c11f-c402-415f-99ea-31cd0e97c32f"),
                            AlreadyUsed = false,
                            Amount = 20,
                            Code = "Awesome"
                        },
                        new
                        {
                            CouponId = new Guid("47721d9a-3ba6-48c1-88f6-e0ba1cd3fe4d"),
                            AlreadyUsed = false,
                            Amount = 100,
                            Code = "AlmostFree"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
